
name: Evidence Collection (GCP)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"  # daily at 03:00 UTC

jobs:
  collect-evidence:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp_creds.json
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Create creds file for SDK libraries
        run: echo "${{ secrets.GCP_SA_KEY }}" > gcp_creds.json

      - name: Install libs
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-asset google-cloud-logging google-cloud-resource-manager google-cloud-iam

      - name: Run Level1 scripts
        run: |
          cd Level1/evidence_scripts
          chmod +x gcp_firewall_rules_export.sh
          python gcp_iam_policy_export.py || true
          python gcp_audit_log_export.py || true
          python gcp_project_config_snapshot.py || true
          ./gcp_firewall_rules_export.sh || true

      - name: Run Level2 scripts
        run: |
          cd $GITHUB_WORKSPACE/Level2/evidence_scripts
          chmod +x gcp_vpc_network_audit.sh
          python gcp_iam_service_account_audit.py || true
          python gcp_logging_sink_export.py || true
          ./gcp_vpc_network_audit.sh || true

      - name: Archive evidence
        run: |
          mkdir -p evidence_output
          find . -type f -name "evidence_*.*" -exec mv {} evidence_output/ \;
          tar -czf evidence_bundle_$(date -u +%Y%m%dT%H%M%SZ).tar.gz evidence_output
          shasum -a 256 evidence_bundle_*.tar.gz > evidence_bundle_*.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: evidence-bundle
          path: |
            evidence_bundle_*.tar.gz
            evidence_bundle_*.sha256
